services:
  - type: web
    name: phcoin-classifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --timeout 120
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: 3.9.12
    disk:
      name: model-storage
      mountPath: /opt/render/project/src/models
      sizeGB: 1 